tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"

brew "git"
brew "htop"
brew "jq"
brew "openssl"
brew "reattach-to-user-namespace"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "xz"
brew "zsh"

cask '1password'
cask 'alfred'
cask 'bettertouchtool'
cask 'docker'
cask 'dropbox'
cask 'github-desktop'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'spotify'
cask 'virtualbox'
cask 'vlc'

